Forex_Update/Models/Promocode.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forex_Update.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promocode
    {
        public int Id { get; set; }
        public string PromocodeStr { get; set; }
        public string BtcWallet { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}

Forex_Update/Controllers/PromocodesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Forex_Update.Models;
using PagedList;

namespace Forex_Update.Controllers
{
    [Authorize(Roles = "ROLE_ADMIN")]
    public class PromocodesController : Controller
    {
        private Entities db = new Entities();

        // GET: Promocodes


        public ActionResult Index(string search, int? page, bool showInactiveNoUser = false)
        {
            var promocodesWithUsers = from promocode in db.Promocodes
                                      join user in db.AspNetUsers on promocode.UserId equals user.Id into userGroup
                                      from user in userGroup.DefaultIfEmpty()
                                      select new PromocodeUserViewModel
                                      {
                                          Id = promocode.Id,
                                          PromocodeStr = promocode.PromocodeStr,
                                          BtcWallet = promocode.BtcWallet,
                                          UserName = user != null ? user.UserName : String.Empty,
                                          UserId = user != null ? (int?)user.Id : null,
                                          Active = promocode.Active
                                      };

            if (!String.IsNullOrEmpty(search))
            {
                promocodesWithUsers = promocodesWithUsers.Where(p => p.PromocodeStr.Contains(search) ||
                                                                      p.BtcWallet.Contains(search) ||
                                                                      (p.UserName != null && p.UserName.Contains(search)));
            }

            if (showInactiveNoUser)
            {
                promocodesWithUsers = promocodesWithUsers.Where(p => p.UserId == null && p.Active == false);
            }

            int pageSize = 30;
            int pageNumber = (page ?? 1);

            var pagedResult = promocodesWithUsers.OrderBy(p => p.PromocodeStr)
                                                 .ToPagedList(pageNumber, pageSize);

            return View(pagedResult);
        }


        // GET: Promocodes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Promocode promocode = db.Promocodes.Find(id);
            if (promocode == null)
            {
                return HttpNotFound();
            }
            return View(promocode);
        }

        // GET: Promocodes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Promocodes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
     
        public ActionResult Create([Bind(Include = "Id,PromocodeStr,BtcWallet")] Promocode promocode)
        {
            // Check if the promocode already exists
            bool promocodeExists = db.Promocodes.Any(p => p.PromocodeStr == promocode.PromocodeStr);
            if (promocodeExists)
            {
                ModelState.AddModelError("PromocodeStr", "This promocode already exists.");
                return View(promocode);
            }

            if (ModelState.IsValid)
            {
                promocode.Active = false;
                db.Promocodes.Add(promocode);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(promocode);
        }


        // GET: Promocodes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Promocode promocode = db.Promocodes.Find(id);
            if (promocode == null)
            {
                return HttpNotFound();
            }
            return View(promocode);
        }

        // POST: Promocodes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,PromocodeStr,BtcWallet,UserId,Active")] Promocode promocode)
        {
            if (ModelState.IsValid)
            {
                db.Entry(promocode).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(promocode);
        }

        // GET: Promocodes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Promocode promocode = db.Promocodes.Find(id);
            if (promocode == null)
            {
                return HttpNotFound();
            }
            return View(promocode);
        }

        // POST: Promocodes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Promocode promocode = db.Promocodes.Find(id);
            db.Promocodes.Remove(promocode);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Forex_Update/Views/Promocodes/Create.cshtml
@model Forex_Update.Models.Promocode

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Promocode</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PromocodeStr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PromocodeStr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PromocodeStr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BtcWallet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BtcWallet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BtcWallet, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>*@

            @*<div class="form-group">
                @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Active)
                        @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Forex_Update/Views/Promocodes/Delete.cshtml
@model Forex_Update.Models.Promocode

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Promocode</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PromocodeStr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PromocodeStr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BtcWallet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BtcWallet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Forex_Update/Views/Promocodes/Details.cshtml
@model Forex_Update.Models.Promocode

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Promocode</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PromocodeStr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PromocodeStr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BtcWallet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BtcWallet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Forex_Update/Views/Promocodes/Edit.cshtml
@model Forex_Update.Models.Promocode

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Promocode</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.PromocodeStr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PromocodeStr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PromocodeStr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BtcWallet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BtcWallet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BtcWallet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Forex_Update/Views/Promocodes/Index.cshtml
@model IPagedList<Forex_Update.Models.PromocodeUserViewModel>
@using PagedList;
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
}




<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Index", "Promocodes", FormMethod.Get))
{
    <div class="form-group">
        <input type="text" name="search" value="@Request.QueryString["search"]" class="" />
        <button type="submit" class="btn btn-secondary">Filter</button>
    </div>
    <div class="checkbox">
        <label>
            <input type="checkbox" name="showInactiveNoUser" value="true" @(Request.QueryString["showInactiveNoUser"] == "true" ? "checked" : "")> Promocodes Without User
        </label>
    </div>
  

}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().PromocodeStr)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().BtcWallet)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().UserId)
        </th>

        <th>UserName</th>

        <th>
            Used
        </th>
        <th>
            action
        </th>
    </tr>

    @foreach (var item in Model)
    {

        <tr>
            <td>@Html.DisplayFor(modelItem => item.PromocodeStr)</td>


            <td>@Html.DisplayFor(modelItem => item.BtcWallet)</td>

            <td>@Html.DisplayFor(modelItem => item.UserId)</td>
            <!-- Other fields as needed -->

            <td>@Html.DisplayFor(modelItem => item.UserName)</td>

            <td>
                @if (item.Active == true)
                {
                    <span>&#10004;</span> <!-- This is a Unicode checkmark -->
                }
                else
                {
                    <span>&#10006;</span> <!-- This is a Unicode cross mark, you can leave this empty if you prefer -->
                }
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |

            </td>
        </tr>
    }

</table>
@Html.PagedListPager(Model, page => Url.Action("Index", new { page, search = Request.QueryString["search"] }))